# Generated by Django 4.0.2 on 2022-05-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_task_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
