# Generated by Django 4.0.2 on 2022-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_comment_options_alter_comment_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.BooleanField(default=True),
        ),
    ]
